locale = "en"
label = "English"
direction = "ltr"
weight = 1

title = "Oscar Pitcho"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Oscar Pitcho"
  links = [
    { email = "mailto:oscar.pitcho@live.com" },
    { github = "https://github.com/opitcho" },
    { linkedin = "https://linkedin.com/in/opitcho" },
  ]
